[log]
output = "/var/log/revad/revad-cephmount.log"

[shared]
gatewaysvc =  "localhost:9142"
jwt_secret = "_redacted_"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:21003"

[grpc.interceptors.notrashbin]
[grpc.interceptors.noversions]

[grpc.services.storageprovider]
driver = "cephmount"
mount_path = "/winspaces"
mount_id = "doyletest"
data_server_url =  "http://cbox-dataserver-alias.cern.ch:22003/data" 

[grpc.services.storageprovider.drivers.cephmount]
fstabentry = "_the entry in /etc/fstab for this CephFS mount_"
root_dir = "/project"
dir_perms = 0o777
file_perms = 0o666

[http]
address = "0.0.0.0:22003"

[http.services.dataprovider]
driver = "cephmount"

[http.services.dataprovider.drivers.cephmount]
fstabentry = "_the entry in /etc/fstab for this CephFS mount_"
root_dir = "/project"
dir_perms = 0o777
file_perms = 0o666
