[log]
output = "/var/log/revad/revad-localfsdev.log"
level = ""


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:38000"

[grpc.services.storageprovider]
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"
driver = "local"
mount_path = "/localfs"
mount_id = "localfs"
data_server_url = "http://localhost:38001/data"
minimum_allowed_path_level_for_share = 0

[grpc.services.storageprovider.drivers.local]
disable_home = true
root = "/var/revalocalstorage/data"
share_folder = "/var/revalocalstorage/shares"

[http]
address = "0.0.0.0:38001"

[http.services.dataprovider]
driver = "local"

[http.services.dataprovider.drivers.local]
root = "/var/revalocalstorage/data"

[tracing]


