[log]
output = "/var/log/revad/revad-collabora.log"


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:18500"

[grpc.services.appprovider]
driver = "wopi"
app_provider_url = "localhost:18500"
# includes ODF, ODF templates, MS legacy formats + RTF, as well as O365 formats (not by default) if enabled
mime_types = ["application/vnd.oasis.opendocument.text", "application/vnd.oasis.opendocument.spreadsheet", "application/vnd.oasis.opendocument.presentation", "application/vnd.oasis.opendocument.text-template", "application/vnd.oasis.opendocument.spreadsheet-template", "application/vnd.oasis.opendocument.presentation-template", "application/msword", "application/vnd.ms-excel", "application/vnd.ms-powerpoint", "application/vnd.visio", "image/vnd.dxf", "text/rtf", "text/csv", "image/svg+xml", ]

[grpc.services.appprovider.drivers.wopi]
iop_secret = "your_value_here"
wopi_url = "https://wopitest.cernbox.cern.ch:8443"
app_name = "Collabora"
app_url = "https://wopidev.cernbox.cern.ch:9980"
folder_base_url = "https://test.cernbox.cern.ch"
app_icon_uri = "https://test.cernbox.cern.ch/cernbox/theme-cernbox-1.0.4/assets/collabora-line.svg"
insecure_connections = true

[tracing]

