[log]
output = "/var/log/revad/revad-o365-cloud.log"


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:18504"

[grpc.services.appprovider]
driver = "wopi"
app_provider_url = "localhost:18504"
mime_types = ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "application/vnd.openxmlformats-officedocument.wordprocessingml.template", "application/vnd.openxmlformats-officedocument.spreadsheetml.template", "application/vnd.openxmlformats-officedocument.presentationml.template", "application/vnd.openxmlformats-officedocument.presentationml.slideshow", "application/msword", "application/vnd.ms-excel", "application/vnd.ms-powerpoint", "application/vnd.visio", "application/vnd.openxmlformats-officedocument.visio", "application/onenote", "application/wopi-validator", "application/wopi-validator-x", "text/csv", ]
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"
language = "en-GB"

[grpc.services.appprovider.drivers.wopi]
iop_secret = "your_value_here"
wopi_url = "https://wopitest.cernbox.cern.ch:8443"
folder_base_url = "https://test.cernbox.cern.ch"
app_name = "MS365"
app_url = "https://onenote.officeapps.live.com"
app_icon_uri = "https://test.cernbox.cern.ch/cernbox/theme-cernbox-1.0.4/assets/msoffice-cloud-line.svg"
insecure_connections = false
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"

[tracing]

