[log]
output = "/var/log/revad/revad-auth-machine.log"


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"

[grpc]
address = "localhost:9166"

[grpc.services.authprovider]
auth_manager = "machine"

[grpc.services.authprovider.auth_managers.machine]
api_key = "your_value_here"

[tracing]
