# this microservice exposes local storage to remote (OCM) users
[log]

output = "/var/log/revad/revad-ocm.log"

[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true

[grpc]
address = "localhost:30000"

[grpc.services.storageprovider]
driver = "ocmoutcoming"
mount_path = "/ocm"
mount_id = "ocm"
data_server_url = "http://localhost:30001/data"

[grpc.services.storageprovider.drivers.ocmoutcoming]
machine_secret = "your_value_here"

[grpc.services.authprovider]
auth_manager = "ocmshares"

[http]
address = "localhost:30001"

[http.services.dataprovider]
driver = "ocmoutcoming"

[http.services.dataprovider.drivers.ocmoutcoming]
machine_secret = "your_value_here"
