[log]
output = "/var/log/revad/revad-projects-i00.log"
level = "info"


[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "your_value_here"
skip_user_groups_in_token = true

[grpc]
address = "0.0.0.0:14500"

[grpc.services.storageprovider]
custom_mime_types_json = "/etc/revad/custom-mimetypes.json"
driver = "eoswrapper"
mount_path = "/eos/project"
mount_id = "eosproject-i00"
data_server_url = "http://localhost:13500/data"
minimum_allowed_path_level_for_share = 5
provides_space_type = "project"

[grpc.services.storageprovider.drivers.eoswrapper]
namespace = "/eos/project/"
quota_node = "/eos/project/"
master_url = "root://eoshomedev.cern.ch"
share_folder = "/Shares"
mount_id_template = "newproject-{{ trimAll \"/\" .Path | substr 0 1 }}"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/var/tmp/reva"
http_client_certfile = "/etc/grid-security/cernbox-hostcert.pem"
http_client_keyfile = "your_value_here"
write_uses_local_temp = false
grpc_auth_key = "your_value_here"
https_auth_key = "your_value_here"
master_grpc_uri = "eoshomedev.cern.ch:50051"
use_grpc = true
allow_insecure = true

[http]
address = "0.0.0.0:13500"

[http.services.dataprovider]
driver = "eoswrapper"

[http.services.dataprovider.drivers.eoswrapper]
namespace = "/eos/project/"
quota_node = "/eos/project/"
master_grpc_uri = "eoshomedev.cern.ch:50051"
mount_id_template = "newproject-{{ trimAll \"/\" .Path | substr 0 1 }}"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/var/tmp/reva"
http_client_certfile = "/etc/grid-security/cernbox-hostcert.pem"
http_client_keyfile = "your_value_here"
write_uses_local_temp = false
use_grpc = true
master_url = "https://eoshomedev.cern.ch:8444"
grpc_auth_key = "your_value_here"
https_auth_key = "your_value_here"
allow_insecure = true

[tracing]

